package RunFailedTestCases;

import org.testng.TestNG;

import java.util.ArrayList;
import java.util.List;

public class FailedTestRunner {

    public void runFailedSuite() {

        TestNG runner = new TestNG();

        List<String> list = new ArrayList<>();

        list.add("./test-output/suite1/testng-failed.xml/"); //suite1 is the suite name in xml file, so after running tests

        runner.setTestSuites(list);                          //a suite1 folder will be created inside test-output folder which will

          runner.run();                                      //contain 2 reports generated by testng(html & xml report) and also contain
                                                             //a testng-failed.xml file which will show details about failed test.

    }
}
